stages:
  - lint
  - test
  - build

default:
  image: node:20
  cache:
    key:
      files:
        - backend/package-lock.json
    paths:
      - backend/node_modules/
  before_script:
    - cd backend
    - npm ci

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  services:
    - name: postgres:16
      alias: postgres
  variables:
    NODE_ENV: test
    PORT: 3000
    LOG_LEVEL: silent
    DB_HOST: postgres
    DB_PORT: 5432
    DB_USERNAME: flowpay
    DB_PASSWORD: flowpay
    DB_NAME: flowpay
    POSTGRES_USER: flowpay
    POSTGRES_PASSWORD: flowpay
    POSTGRES_DB: flowpay
  script:
    - npm run test -- --ci
    - npm run migration:run
    - npm run test:e2e -- --ci

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - backend/dist/
    expire_in: 1 week
